### ISSUE TITLE
Conflict with newer versions of Babel?

### ISSUE THREAD

**Issue by marcohamersma** [reactjs/react-a11y#73]
I'm writing a server that serves some rendered React components, and would like to use react-a11y in my project. However, adding `var a11y = require('react-a11y')` makes the script stop working, it generates the following output:

```
Error: Cannot find module 'babel-runtime/helpers/to-consumable-array'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Marco/Projects/Prototypes/node_modules/react-a11y/dist/index.js:3:26)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Marco/Projects/Prototypes/node_modules/babel-core/lib/babel/api/register/node.js:161:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

It seems to be conflicting because the Babel version I'm using is different, and I'm guessing some part of `react-a11y`s dependencies is expecting some method to (still) exist. I'm not quite sure how to fix this. Perhaps specifying stricter dependencies?

fwiw, my babel version is `5.4.7`

**Comment by mathieumg** [comment]
It's simply that they use `babel-runtime` without properly indicating so in the `package.json` file (it's only a dev dependency now), see: https://github.com/rackt/react-a11y/issues/72

In the meantime, you can `npm install babel-runtime --save` beside `react-a11y` to get it to work.

**Comment by marcohamersma** [comment]
Ah yes, thanks for the workaround. Fixed it for me. I guess this issue is sort of a duplicate now.
